cpu : Intel Alder Lake E-core Gracemont CPU {
  frontend: Frontend {
    bp: Branch Predictor {
      # Source: Chips and Cheese
      l1btb: 1024-entry L1 BTB

      # Source: Chips and Cheese, Intel
      # Intel: "he NLP is backed by the second predictor that includes a 5K
      # entry target array combined with path-based information to make
      # predictions and verify target addresses in three cycles."
      l2btb: 5120-way L2 BTB, 3 cycle latency

      # Source: Chips and Cheese
      ind: >=512-entry Indirect Target Array

      # Source: Intel
      bw: 32B/cycle prediction bandwidth
    }

    l1ic: L1 IC {
      # Source: Chips and Cheese
      itlb: 64-entry fully associative ITLB

      # Source: Chips and Cheese, Intel
      # Intel: "Larger 64KB Instruction Cache with dual 32B reads (32B read per
      # fetch cluster)."
      l1ic: 64KB 8-way L1 IC, 2x32 B/cycle
    }

    # Source: Chips and Cheese
    fq: 2x Fetch Queue
    bp -> fq
    fq -> l1ic

    iq1: Instruction Queue \#1
    l1ic -> iq1

    # Source: Chips and Cheese
    decode1: 3-way Decode \#1
    iq1 -> decode1

    # Source: Chips and Cheese
    uop1: UOP Queue \#1
    decode1 -> uop1

    iq2: Instruction Queue \#2
    l1ic -> iq2

    # Source: Chips and Cheese
    decode2: 3-way Decode \#2
    iq2 -> decode2

    # Source: Chips and Cheese
    uop2: UOP Queue \#2
    decode2 -> uop2

    # Source: Chips and Cheese, Intel
    rename: 5-way Rename {
      Move Elimination
      Zero Idiom
    }
    uop1 -> rename
    uop2 -> rename
  }

  backend: Backend {
    # Source: Chips and Cheese, Intel
    # Intel: "Retirement can be up to eight instructions per cycle for the
    # 256-entry retirement buffer."
    rob: 256-entry ROB, 8-wide retirement

    # Source: Chips and Cheese
    bob: 116-taken-entry 126-not-taken-entry Branch Order Buffer

    rf: Register File {
      # Source: Chips and Cheese
      irf: 214-entry Integer Register File

      # Source: Chips and Cheese
      vrf: 207-entry 128b Vector Register File
    }

    # Source: Chips and Cheese
    sched1: 15-entry ALU Scheduler \#1

    # Source: Chips and Cheese, Intel
    pipe1: Port 0 {
      grid-columns: 1
      ALU
      SHIFT
    }
    rob -> sched1 -> rf.irf -> pipe1

    # Source: Chips and Cheese
    sched2: 16-entry ALU Scheduler \#2

    # Source: Chips and Cheese
    pipe2: Port 1 {
      grid-columns: 1
      ALU
      SHIFT
      INT MUL
      INT DIV
    }
    rob -> sched2 -> rf.irf -> pipe2

    # Source: Chips and Cheese
    sched3: 16-entry ALU Scheduler \#3

    # Source: Chips and Cheese, Intel
    pipe3: Port 2 {
      grid-columns: 1
      ALU
      SHIFT
      INT MUL
      INT DIV
      PDEP
    }
    rob -> sched3 -> rf.irf -> pipe3

    # Source: Chips and Cheese
    sched4: 15-entry ALU Scheduler \#4

    # Source: Chips and Cheese, Intel
    pipe4: Port 3 {
      grid-columns: 1
      ALU
      SHIFT
    }
    rob -> sched4 -> rf.irf -> pipe4

    # Source: Chips and Cheese
    # Intel: "The fifth integer reservation station holds jumps and store data
    # operations. This structure is banked and can schedule two uops of each
    # type every cycle; two store data on ports 08 and 09, and two jumps on
    # ports 30 and 31"
    sched5: 42-entry Branch/Store Data Scheduler \#5

    # Source: Chips and Cheese, Intel
    pipe5: Port 30 {
      JMP/Branch
    }
    rob -> sched5 -> rf.irf -> pipe5

    # Source: Chips and Cheese, Intel
    pipe6: Port 31 {
      JMP/Branch
    }
    rob -> sched5 -> rf.irf -> pipe6

    # new Chips and Cheese new post (Meteor Lake’s E-Cores: Crestmont Makes Incremental Progress)
    # the scheduler organization was different:
    # "Intel’s optimization guide says Crestmont and Gracemont serve store data
    # and jump operations with the same queue. I missed this in 2021 because
    # that possibility didn’t cross my mind."
    # Source: Chips and Cheese, Intel
    pipe7: Port 12 {
      Store AGU
    }
    rob -> sched5 -> rf.irf -> pipe7

    # Source: Chips and Cheese, Intel
    pipe8: Port 13 {
      Store AGU
    }
    rob -> sched5 -> rf.irf -> pipe8

    # Source: Chips and Cheese
    nsq1: 22-entry AGU Non-Scheduling Queue \#1

    # Source: Chips and Cheese
    sched6: 22-entry AGU Scheduler \#6

    # Source: Chips and Cheese, Intel
    pipe9: Port 10 {
      Load AGU
    }
    rob -> nsq1 -> sched6 -> rf.irf -> pipe9

    # Source: Chips and Cheese, Intel
    pipe10: Port 11 {
      Load AGU
    }
    rob -> nsq1 -> sched6 -> rf.irf -> pipe10

    # Source: Chips and Cheese, Intel
    pipe11: Port 8 {
      Store Data
    }
    rob -> nsq1 -> sched6 -> rf.irf -> pipe11

    # Source: Chips and Cheese, Intel
    pipe12: Port 9 {
      Store Data
    }
    rob -> nsq1 -> sched6 -> rf.irf -> pipe12

    lsu: LSU {
      # Source: Chips and Cheese
      80-entry Load Queue
      50-entry Store Queue

      # Source: jiegec
      4 cycle load to use latency
      3 cycle load to use latency in pointer chasing
    }

    pipe7 -> lsu
    pipe8 -> lsu
    pipe9 -> lsu
    pipe10 -> lsu
    pipe11 -> lsu
    pipe12 -> lsu

    # Source: Chips and Cheese
    nsq2: 56-entry FP Non-Scheduling Queue \#2

    # Source: Chips and Cheese
    sched7: 18-entry FStore Scheduler \#7

    # Source: Chips and Cheese, Intel
    pipe13: Port 28 {
      FP Store Data
    }
    rob -> nsq2 -> sched7 -> rf.vrf -> pipe13

    # Source: Chips and Cheese, Intel
    pipe14: Port 29 {
      FP Store Data
    }
    rob -> nsq2 -> sched7 -> rf.vrf -> pipe14

    # Source: Chips and Cheese
    sched8: 35-entry FP/Vector Scheduler \#8

    # Source: Chips and Cheese, Intel
    pipe15: Port 20 {
      grid-columns: 1
      INT Vec ALU
      INT Vec MUL
      FMA
      FADD
      FMUL
      AES
      FDIV
      SHA
    }
    rob -> nsq2 -> sched8 -> rf.vrf -> pipe15

    # Source: Chips and Cheese, Intel
    pipe16: Port 21 {
      grid-columns: 1
      INT Vec ALU
      FMA
      FADD
      FMUL
      AES
    }
    rob -> nsq2 -> sched8 -> rf.vrf -> pipe16

    # Source: Chips and Cheese, Intel
    pipe17: Port 22 {
      INT Vec ALU
    }
    rob -> nsq2 -> sched8 -> rf.vrf -> pipe17
  }

  frontend.rename -> backend.rob
  frontend.rename -> backend.bob

  mem: Memory {
    l1: L1 DC {
      # Source: Chips and Cheese
      # Chips and Cheese: 48-entry
      # Intel: 32-entry
      l1dtlb: 32-entry fully associative L1 DTLB

      # Source: Chips and Cheese
      # Intel: "4-cycle load-to-use latency."
      l1dc: 32KB 8-way L1DC, 4 cycle load-to-use latency
    }

    # Source: Chips and Cheese, Intel
    # Intel: "The main STLB is 2048 entries 4-way set associative and caches
    # 4KB and 2MB translations. Additionally, Gracemont microarchitecture has
    # an 8-entry fully associative structure for GB translations"
    l2tlb: 2048-entry 4-way 4K/2M/4M page, 8-entry fully associative 1G page L2 TLB

    l2: L2 {
      # Source: Chips and Cheese, Intel
      # Intel: "The L2 cache delivers 64 bytes of data per cycle at a latency of
      # 17 cycles, and that bandwidth is shared among four cores."
      l2dc: 2MB 16-way Shared L2 Cache, 17 cycle latency

      # Source: Intel
      # Intel: "Pipelined Page Miss Handler capable of handling 4 concurrent
      # page walks."
      ptw: 4 page table walkers
    }

    # Source: Chips and Cheese, Intel
    l1 -> l2: 64B/cycle shared among 4 cores

    l3: L3 {
      # Source: Chips and Cheese
      l3dc: 30MB 12-way L3 Cache
    }
    l2 -> l3
  }
  frontend.l1ic -> mem.l2
  backend.lsu -> mem.l1

  info: |md
    Drawn by Jiajie Chen @jiegec

    Based on data from Chips and Cheese, Intel
  |
}