site_name: CPU Microarchitecture Diagrams
site_url: https://jia.je/cpu
repo_url: https://github.com/jiegec/cpu
edit_uri: edit/master/docs/
nav:
  - CPU Microarchitecture Diagrams: index.md
  - Comparisons across microarchitectures: comparison.md
  - Reverse engineered conditional branch predictors: cbp.md
  - AArch64:
      - ARM Cortex-A75: cortex_a75.md
      - ARM Cortex-A77: cortex_a77.md
      - ARM Cortex-X1: cortex_x1.md
      - ARM Cortex-X2: cortex_x2.md
      - ARM Cortex-X3: cortex_x3.md
      - ARM Cortex-X4: cortex_x4.md
      - ARM Cortex-X925: cortex_x925.md
      - ARM Neoverse-V2: neoverse_v2.md
      - Ampere One: ampere_one.md
      - Apple M1 P-core (Firestorm): firestorm.md
      - Apple M2 P-core (Avalanche): avalanche.md
      - Apple M3 P-core: m3_pcore.md
      - Apple M4 P-core: m4_pcore.md
      - Phytium Xiaomi: xiaomi.md
      - Qualcomm Oryon: oryon.md
  - AMD64:
      - AMD Zen1: zen1.md
      - AMD Zen2: zen2.md
      - AMD Zen3: zen3.md
      - AMD Zen4: zen4.md
      - AMD Zen5: zen5.md
      - Intel Skylake: skylake.md
      - Intel Ice Lake (Sunny Cove): sunny_cove.md
      - Intel Alder Lake P-core (Golden Cove): golden_cove.md
      - Intel Alder Lake E-core (Gracemont): gracemont.md
      - Intel Meteor Lake P-core (Redwood Cove): redwood_cove.md
      - Intel Meteor Lake E-core (Crestmont): crestmont.md
      - Intel Lunar Lake P-core (Lion Cove): lion_cove.md
      - Intel Lunar Lake E-core (Skymont): skymont.md
  - LoongArch64:
      - Loongson 3A6000: 3a6000.md
  - RISC-V64:
      - SiFive P550: p550.md
      - SiFive P870: p870.md
  - Dieshot: dieshot.md
theme:
  custom_dir: overrides
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - navigation.expand
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.highlight
    - search.share
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox:
      height: 100vh
  - search
  - offline
  - social:
      cards_layout_options:
        font_family: Noto Sans SC
  - macros
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  analytics:
    provider: custom
copyright: Copyright &copy; 2024 Jiajie Chen
