site_name: CPU Microarchitecture Diagrams
site_url: https://jia.je/cpu
repo_url: https://github.com/jiegec/cpu
edit_uri: edit/master/docs/
nav:
  - Home: index.md
  - AArch64:
    - Apple M1 P-core (Firestorm): firestorm.md
    - Apple M2 P-core (Avalanche): avalanche.md
    - Apple M3 P-core: m3_pcore.md
    - Apple M4 P-core: m4_pcore.md
    - Qualcomm Oryon: oryon.md
  - AMD64:
    - AMD Zen3: zen3.md
    - AMD Zen4: zen4.md
    - AMD Zen5: zen5.md
    - Intel Alder Lake P-core (Golden Cove): golden_cove.md
    - Intel Alder Lake E-core (Gracemont): gracemont.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - navigation.expand
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox:
      height: 100vh
  - search
  - offline
  - social:
      cards_font: Noto Sans SC
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  analytics:
    provider: google
    property: G-3109FRSVTT
copyright: Copyright &copy; 2024 Jiajie Chen
