cpu : AMD Zen2 CPU {
  frontend: Frontend {
    bp: Branch Predictor {
      # Source: Chips and Cheese, AMD
      l1btb: 16-entry(8 forward, 8 backward) L1 BTB, zero bubbles

      # Source: Chips and Cheese, AMD
      l2btb: 512-entry L2 BTB, one bubble

      # Source: Chips and Cheese, AMD
      l3btb: 7168-entry L3 BTB, four bubbles

      # Source: Chips and Cheese, AMD
      indir: 1024-entry Indirect Target Array

      # Source: Chips and Cheese, AMD
      ras: 32-entry Return Address Stack

      # Source: AMD
      hp: hashed perceptron L1 branch predictor

      # Source: AMD
      tage: TAGE L2 branch predictor

      # Source: AMD
      penalty: 12-18 cycle branch misprediction latency, 16 typical
    }

    l1ic: L1 IC {
      # Source: Chips and Cheese, AMD
      l1itlb: 64-entry L1 ITLB

      # Source: Chips and Cheese, AMD
      l2itlb: 512-entry L2 ITLB

      # Source: Chips and Cheese, AMD
      l1ic: 32KB 8-way L1 IC
    }

    # Source: Chips and Cheese
    fq: 64-entry Fetch Queue
    bp -> fq
    fq -> l1ic

    iq: 20-entry x 16B Instruction Queue
    l1ic -> iq

    # Source: Chips and Cheese
    decode: 4-way Decode
    iq -> decode

    # Source: Chips and Cheese, AMD
    uopc: 4096-entry 8-way UOP Cache
    decode -> uopc
    bp -> uopc

    # Source: Chips and Cheese
    uop: UOP Queue
    uopc -> uop: 8 fused instructions/cycle
    decode -> uop: 4 instructions/cycle

    # Source: Chips and Cheese
    rename: 5-way Rename {
      Move Elimination
      Zero Idiom
    }
    uop -> rename
  }

  backend: Backend {
    # Source: Chips and Cheese, AMD
    rob: 224-entry ROB

    # Source: Chips and Cheese, jiegec
    # Chips and Cheese: 32 taken, 128 not taken
    # jiegec: 32 taken, 138 not taken
    bob: 32-taken-entry 138-not-taken-entry Branch Order Buffer

    rf: Register File {
      # Source: Chips and Cheese, AMD
      # Source: jiegec, 132 speculative
      irf: 180-entry Integer Register File

      # Source: jiegec, 138 speculative
      flagsrf: 138-entry Flags Register File

      # Source: Chips and Cheese, AMD
      # Source: jiegec, 144 speculative
      vrf: 160-entry FP/Vector Register File
    }

    # Source: Chips and Cheese, AMD
    # Source: jiegec, 64(=16*4) sched size for alu
    sched1: 16-entry ALU Scheduler \#1

    # Source: Chips and Cheese
    pipe1: Pipe \#1 {
      ALU
      Branch
    }
    sched1 -> rf -> pipe1

    # Source: Chips and Cheese, AMD
    sched2: 16-entry ALU Scheduler \#2

    # Source: Chips and Cheese
    pipe2: Pipe \#2 {
      ALU
      INT MUL
    }
    sched2 -> rf -> pipe2

    # Source: Chips and Cheese, AMD
    sched3: 16-entry ALU Scheduler \#3

    # Source: Chips and Cheese
    pipe3: Pipe \#3 {
      ALU
      INT DIV
      CRC
    }
    sched3 -> rf -> pipe3

    # Source: Chips and Cheese, AMD
    sched4: 16-entry ALU Scheduler \#4

    # Source: Chips and Cheese
    pipe4: Pipe \#4 {
      ALU
      Branch
    }
    sched4 -> rf -> pipe4

    # Source: Chips and Cheese, AMD
    # Source: jiegec, 28 sched size for load & store
    sched5: 28-entry AGU Scheduler \#5

    # Source: Chips and Cheese
    pipe5: Pipe \#5 {
      Load AGU
      Store AGU
    }
    sched5 -> rf -> pipe5

    # Source: Chips and Cheese
    pipe6: Pipe \#6 {
      Load AGU
      Store AGU
    }
    sched5 -> rf -> pipe6

    # Source: Chips and Cheese
    pipe7: Pipe \#7 {
      Store AGU
    }
    sched5 -> rf -> pipe7

    lsu: LSU {
      # Source: Chips and Cheese
      # 44-entry Pre-L1D Access Load Queue
      # (44+72)-entry Load Queue
      # Source: AMD: "The LS unit includes a 44-entry load queue (LDQ)"
      # Source: jiegec, see /data/zen2/lsu.csv:
      # pattern 0: spike at 116, equals to 44+72
      72-entry Load Queue
      # Source: Chips and Cheese, AMD
      # AMD: "The LS unit utilizes a 48-entry store queue which holds stores
      # from dispatch until the store data can be written to the data cache."
      # Source: jiegec, see /data/zen2/lsu.csv, pattern 2 & 3, spike at 48
      48-entry Store Queue

      # Source: jiegec
      # Source: AMD
      # "The LS unit contains three largely independent pipelines enabling the
      # execution of two 256-bit load memory operations and one 256-bit store
      # memory operation per cycle."
      2x 256b Load Pipe
      1x 256b Store Pipe
    }

    pipe5 -> lsu
    pipe6 -> lsu
    pipe7 -> lsu

    rob -> sched1
    rob -> sched2
    rob -> sched3
    rob -> sched4
    rob -> sched5

    # Source: Chips and Cheese
    # Source: jiegec, 100(64+36) sched size for fp
    nsq: 64-entry Non/Pre-Scheduling Queue
    rob -> nsq

    # Source: Chips and Cheese
    sched6: 36-entry Vector/FP Scheduler \#6
    nsq -> sched6

    # Source: Chips and Cheese
    pipe8: Pipe \#8 {
      FMA
      INT Vec ALU
      INT Vec MUL
      AES
    }
    sched6 -> rf -> pipe8

    # Source: Chips and Cheese
    pipe9: Pipe \#9 {
      FADD
      INT Vec ALU
      Vec Shuffle
      AES
    }
    sched6 -> rf -> pipe9

    # Source: Chips and Cheese
    pipe10: Pipe \#10 {
      FADD
      FStore
      Vec Shuffle
      Vec Shift
    }
    sched6 -> rf -> pipe10 -> lsu

    # Source: Chips and Cheese
    pipe11: Pipe \#11 {
      FADD
      INT Vec ALU
      FDIV
    }
    sched6 -> rf -> pipe11
  }
  frontend.rename -> backend.rob
  frontend.rename -> backend.bob

  mem: Memory {
    l1: L1 DC {
      # Source: Chips and Cheese, AMD
      l1dtlb: 64-entry L1 DTLB

      # Source: Chips and Cheese, AMD
      l2dtlb: 2048-entry L2 DTLB

      # Source: Chips and Cheese, AMD
      l1dc: 32KB 8-way L1DC

      # Source: Chips and Cheese
      mshr: 22-entry MSHR

      # Source: AMD
      ptw: 2 Page Table Walkers
    }

    l2: L2 {
      # Source: Chips and Cheese, AMD
      l2dc: 512KB 8-way L2 Cache
    }

    # Source: Chips and Cheese
    l1 -> l2: 32B/cycle

    l3: L3 {
      # Source: Chips and Cheese
      l3dc: 16MB 16-way L3 Cache
    }
    l2 -> l3
  }
  frontend.l1ic -> mem.l2
  backend.lsu -> mem.l1

  info: |md
    Drawn by Jiajie Chen @jiegec

    Based on data from Chips and Cheese, Anandtech and AMD
  |
}