cpu : AMD Zen4 CPU {
  frontend: Frontend {
    bp: Branch Predictor {
      # Source: Chips and Cheese, AMD
      l1btb: 1536-entry L1 BTB

      # Source: Chips and Cheese, AMD
      l2btb: 7168-entry L2 BTB

      # Source: Chips and Cheese
      indir: 3072-entry Indirect Target Array

      # Source: Chips and Cheese
      ras: 32-entry Return Address Stack

      # Source: AMD
      2 taken predictions per cycle
    }

    l1ic: L1 IC {
      # Source: Chips and Cheese, AMD
      l1itlb: 64-entry L1 ITLB

      # Source: Chips and Cheese, AMD
      l2itlb: 512-entry L2 ITLB

      # Source: Chips and Cheese, AMD
      l1ic: 32KB 8-way L1 IC
    }

    fq: Fetch Queue
    bp -> fq
    fq -> l1ic

    iq: Instruction Queue
    l1ic -> iq

    # Source: Chips and Cheese, AMD
    decode: 4-way Decode
    iq -> decode

    # Source: Chips and Cheese, AMD
    uopc: 6912-entry 12-way UOP Cache, max 9 ops per entry
    decode -> uopc
    bp -> uopc

    # Source: Chips and Cheese
    uop: UOP Queue
    uopc -> uop
    decode -> uop

    # Source: Chips and Cheese
    rename: 6-way Rename {
      Move Elimination
      Zero Idiom
    }
    uop -> rename
  }

  backend: Backend {
    # Source: Chips and Cheese, AMD
    rob: 320-entry ROB

    # Source: Chips and Cheese
    bob: 62-taken-entry 118-not-taken-entry Branch Order Buffer

    rf: Register File {
      # Source: Chips and Cheese, AMD
      irf: 224-entry Integer Register File

      # Source: Chips and Cheese, AMD
      # 238 reported by Chips and Cheese
      # 126 reported by AMD
      flagsrf: 126-entry Flags Register File

      # Source: Chips and Cheese, AMD
      vmaskrf: (52+16)-entry Vector Mask Register File

      # Source: Chips and Cheese, AMD
      vrf: 192-entry 512b Vector Register File
    }

    # Source: Chips and Cheese, AMD
    sched1: 24-entry Scheduler \#1

    # Source: Chips and Cheese
    pipe1: Pipe \#1 {
      ALU
    }
    sched1 -> rf -> pipe1

    # Source: Chips and Cheese
    pipe2: Pipe \#2 {
      Branch
    }
    sched1 -> rf -> pipe2

    # Source: Chips and Cheese, AMD
    sched2: 24-entry Scheduler \#2

    # Source: Chips and Cheese
    pipe3: Pipe \#3 {
      ALU
    }
    sched2 -> rf -> pipe3

    # Source: Chips and Cheese
    pipe4: Pipe \#4 {
      AGU
    }
    sched2 -> rf -> pipe4

    # Source: Chips and Cheese, AMD
    sched3: 24-entry Scheduler \#3

    # Source: Chips and Cheese
    pipe5: Pipe \#5 {
      ALU
    }
    sched3 -> rf -> pipe5

    # Source: Chips and Cheese
    pipe6: Pipe \#6 {
      AGU
    }
    sched3 -> rf -> pipe6

    # Source: Chips and Cheese, AMD
    sched4: 24-entry Scheduler \#4

    # Source: Chips and Cheese
    pipe7: Pipe \#7 {
      ALU
      Branch
    }
    sched4 -> rf -> pipe7

    # Source: Chips and Cheese
    pipe8: Pipe \#8 {
      AGU
    }
    sched4 -> rf -> pipe8

    lsu: LSU {
      # Source: Chips and Cheese, AMD
      # 136 (Load Validation Queue) & 88 (Load Execution Queue) reported by Chips and Cheese
      # 88 reported by AMD
      136-entry Load Validation Queue
      88-entry Load (Execution) Queue
      64-entry Store Queue

      # Source: AMD
      # 3 loads per cycle (max 2 if 256b)
      # 2 stores per cycle (max 1 if 256b)
      3 Load per cycle (2 if 256b)
      2 Store per cycle (1 if 256b)
    }

    pipe4 -> lsu
    pipe6 -> lsu
    pipe8 -> lsu

    rob -> sched1
    rob -> sched2
    rob -> sched3
    rob -> sched4

    # Source: Chips and Cheese, AMD
    nsq: 64-entry Non/Pre-Scheduling Queue
    rob -> nsq

    # Source: Chips and Cheese, AMD
    sched5: 32-entry Scheduler \#5
    nsq -> sched5

    # Source: Chips and Cheese
    pipe9: Pipe \#9 {
      FMA
    }
    sched5 -> rf -> pipe9

    # Source: Chips and Cheese
    pipe10: Pipe \#10 {
      FADD
    }
    sched5 -> rf -> pipe10

    # Source: Chips and Cheese
    pipe11: Pipe \#11 {
      FStore
      F2I
    }
    sched5 -> rf -> pipe11 -> lsu

    # Source: Chips and Cheese, AMD
    sched6: 32-entry Scheduler \#6
    nsq -> sched6

    # Source: Chips and Cheese
    pipe12: Pipe \#12 {
      FMA
    }
    sched6 -> rf -> pipe12

    # Source: Chips and Cheese
    pipe13: Pipe \#13 {
      FADD
    }
    sched6 -> rf -> pipe13

    # Source: Chips and Cheese, AMD
    pipe14: Pipe \#14 {
      # FStore + F2I reported by Chips and Cheese
      # FStore reported by AMD
      FStore
    }
    sched6 -> rf -> pipe14 -> lsu
  }
  frontend.rename -> backend.rob
  frontend.rename -> backend.bob

  mem: Memory {
    l1: L1 DC {
      # Source: Chips and Cheese, AMD
      l1dtlb: 72-entry L1 DTLB

      # Source: Chips and Cheese, AMD
      l2dtlb: 3072-entry L2 DTLB

      # Source: Chips and Cheese, AMD
      l1dc: 32KB 8-way L1DC
    }

    l2: L2 {
      # Source: Chips and Cheese, AMD
      l2dc: 1MB 8-way L2 Cache, 14 cycle latency
    }

    # Source: Chips and Cheese, AMD
    l1 -> l2: 32B/cycle

    l3: L3 {
      # Source: Chips and Cheese, AMD
      l3dc: 32MB (4MB/core) 16-way L3 Cache, 50 cycle latency
    }
    l2 -> l3
  }
  frontend.l1ic -> mem.l2
  backend.lsu -> mem.l1

  info: |md
    Drawn by Jiajie Chen @jiegec

    Based on data from Chips and Cheese, Anandtech and AMD
  |
}