name: publish
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for git history
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - uses: Gr1N/setup-poetry@v9
      - run: curl -fsSL https://d2lang.com/install.sh | sh -s --
      - run: poetry install
      - run: cd docs && ./build.sh
      - run: poetry run mkdocs gh-deploy --force
